# Generated by Django 2.0.3 on 2018-03-15 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20, verbose_name='城市名称')),
                ('city_desc', models.CharField(max_length=200, verbose_name='城市描述')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'city_dict',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, verbose_name='企业名称')),
                ('business_category', models.CharField(choices=[('1', '互联网/电子商务'), ('2', '金融/投资/证券'), ('3', '房地产')], max_length=1, verbose_name='行业分类')),
                ('profile_picture', models.ImageField(default='employer/default-profile.jpg', upload_to='employer/%Y/%m', verbose_name='企业头像')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('company_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.CityDict', verbose_name='企业所在地')),
            ],
            options={
                'verbose_name': '企业信息',
                'verbose_name_plural': '企业信息',
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=20, verbose_name='职位名称')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('deploy_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.CompanyInfo', verbose_name='发布企业')),
                ('job_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.CityDict', verbose_name='工作地点')),
            ],
            options={
                'verbose_name': '职位信息',
                'verbose_name_plural': '职位信息',
                'db_table': 'job_info',
            },
        ),
    ]
